name: testing google-github-actions

on:
  push:



jobs:
  job_id:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/spreadsheets,https://www.googleapis.com/auth/drive.readonly'
        project_id: 'gsheet-bican'
        workload_identity_provider: 'projects/497900577721/locations/global/workloadIdentityPools/github/providers/my-repo-1'
        service_account: 'bican-gsheet-service@gsheet-bican.iam.gserviceaccount.com'

    - name: Check if Output Exists
      if: ${{ steps.auth.outputs.access_token != '' }}
      run: echo "Output exists"

    - name: List Revisions of Google Sheet
      run: |
        curl -H "Authorization: Bearer ${{ steps.auth.outputs.access_token }}" \
          "https://www.googleapis.com/drive/v3/files/1gFPuDW8U_LvKiyQ1B6LqMh0E7REEy68lxR914bkhMMg/revisions" > revisions.json
        cat revisions.json


    - id: 'download'
      run: |-
        curl "https://www.googleapis.com/drive/v3/files/1gFPuDW8U_LvKiyQ1B6LqMh0E7REEy68lxR914bkhMMg/export?mimeType=text/csv&sheet=Sheet1" \ #"https://docs.google.com/spreadsheets/export?id=1gFPuDW8U_LvKiyQ1B6LqMh0E7REEy68lxR914bkhMMg&revision=7&exportFormat=xlsx" \
          --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}" \
          -o google_spreadsheet.csv
#          -o sheet_data_revision.xlsx
        cat google_spreadsheet.csv


    - name: Upload Downloaded File
      uses: actions/upload-artifact@v4
      with:
        name: downloaded_file
        path: |
          revisions.json
          sheet_data_revision.xlsx


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: pip install openpyxl

#    - name: Display Excel File Content
#      run: python read_excel.py

#    - name: Install Google API Client Library
#      run: pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

#    - name: Download Google Sheet
#      run: python download_sheet.py