name: testing google-github-actions

on:
  push:



jobs:
  job_id:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        project_id: 'gsheet-bican'
        workload_identity_provider: 'projects/497900577721/locations/global/workloadIdentityPools/github/providers/my-repo-1'
        service_account: 'bican-gsheet-service@gsheet-bican.iam.gserviceaccount.com'

    - id: 'access-secret'
      run: |-
        curl https://secretmanager.googleapis.com/v1/projects/gsheet-bican/secrets/my-secret/versions/1:access \
          --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"


#    - name: Install Google API Client Library
#      run: pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

#    - name: Download Google Sheet
#      run: python download_sheet.py